### PR TITLE
Follow redirect : fix for issue #12

### PR DESCRIPTION
**Pull request by dmargery**
Hi,

this fixes an issue for redirects not being folled. It also explains double load behaviour on resource creation that I never investigated.

David

### CODE REVIEW

**Comment by crohr** [comment]
Hi David,

I don't think you should remove the 201 & 202 handling code, because these are used when creating a new resource, to fetch the content of the newly created resource. You may have double loading since restfully may think that it only has a partial view of the resource on the first load (probably a bug elsewhere).

However you may indeed want to add support for 301 & 302 on the same line.

**Comment by dmargery** [comment]
Hello,

I'm not convinced 201 and 202 responses should imply a GET to the Location of the created request unconditionally. I would only do this if the body is empty or Resource building from the body fails, as uncomplete answers are already handled by the media-type.

Hence an update where [201,202] and [301,302] are kept separate in the code for appropriate debug messages, and in the spec to anticipate the fact that proper [201,202] handling might become more complex

David

**Comment by crohr** [comment]
I'm happy with this, and maybe we could indeed improve the handling of 201 and 202 requests.

There seems to be a syntax issue with the submitted code, so can you fix it and push again?

And finally, could you squash the irrelevant commits from your PR (with `git rebase -i` for instance)?

Thanks!

**Comment by dmargery** [comment]
Made a few mistakes when rebasing, so all comments in this tread are not easy to follow, but this pull request should be the clean and final one.

David

**Comment by crohr** [comment]
v1.1.1 has been pushed to rubygems.org

**Comment by dmargery** [comment]
Le 11/06/2015 15:31, Cyril Rohr a écrit :
> v1.1.1 has been pushed to rubygems.org
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crohr/restfully/pull/13#issuecomment-111136148>.
> 

Thank you.

David

-- 
David Margery <><   (jabber/mail:David.Margery@inria.fr)
Ingénieur de Recherche
Directeur technique d'ALADDIN-G5K pour Grid'5000
Centre de recherche INRIA Rennes - Bretagne Atlantique, France
Equipe Myriads, bureau E201, niveau vert, tel +33 2 99 84 25 12

**Pull request merged**
