### PR TITLE
Optimize single item retrieval from collection, using direct fetch when possible

### PR DESCRIPTION
**Pull request by crohr**
Alternate option for issue discussed in #8. Not tested (I don't have access to Grid5000 API), but hopefully it should work.

### CODE REVIEW

**Comment by dmargery** [comment]
Hello,

I like the approach very much, and it work well on Grid'5000's job API. I think you should merge and release

David

**Comment by crohr** [comment]
Will release shortly, but do you still need support for ruby 1.8.7 (I had to downgrade rest-client and others to make the tests pass on 1.8.7)?

**Comment by dmargery** [comment]
Le 13/02/2015 14:39, Cyril Rohr a écrit :
> Will release shortly, but do you still need support for ruby 1.8.7 (I
> had to downgrade rest-client and others to make the tests pass on 1.8.7)?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crohr/restfully/pull/11#issuecomment-74254335>.
> 
Hello,

I don't believe ruby 1.8 is still needed. On Grid'5000 frontends,
restfully is running on a ruby 1.9 version, and I hope that on user
controlled machines, nobody is still stuck with ruby 1.8.

When used as a library or in system tests, might still depend on ruby
1.8, but I'm happy to discover these cases and fix them.

Regards,

David
-- 
David Margery <><   (jabber/mail:David.Margery@inria.fr)
Ingénieur de Recherche
Directeur technique d'ALADDIN-G5K pour Grid'5000
Centre de recherche INRIA Rennes - Bretagne Atlantique, France
Equipe Myriads, bureau E201, niveau vert, tel +33 2 99 84 25 12

**Comment by crohr** [comment]
Great, v1.1.0 has now been released on rubygems.org.

**Pull request merged**
